language: node_js
node_js: 8
cache:
  directories:
    - ~/.npm
    - node_modules
script:
  - npm run lint
  - npm run test
after_success:
  - npm run coverage
  - npm run build
  - npm run release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
